options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build Docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA',
    '.'
  ]

# Run app integration tests
# Start Container
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',
    '-d',
    '-p', '5000:5000',
    '--name', 'test-container',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA'
  ]

# Test HTTP response
- name: 'gcr.io/cloud-builders/curl'
  args: [
    '-f',  # Fail on HTTP errors
    '--retry', '3',
    '--retry-delay', '10',
    'http://localhost:5000'
  ]

# Push to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA'
  ]

# Deploy to k8s
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment/coinprice-server',
    'crypto-price-server=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

substitutions:
  _REGION: us-central1
  _REPO_NAME: devops-example-coinprice
  _CLUSTER_NAME: coinprice-cluster