options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build Docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA',
    '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:latest',
    '.'
  ]

# Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '--all-tags',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server'
  ]

# Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment/coinprice-server',
    'coinprice-server=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/coinprice-server:$COMMIT_SHA',
    '-n',
    'coinprice'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

# Verify deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'status', 'deployment/coinprice-server', '-n', 'coinprice']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

substitutions:
  _REGION: us-central1
  _ZONE: us-central1-a
  _REPO_NAME: devops-example-coinprice
  _CLUSTER_NAME: coinprice-cluster

timeout: 1800s