# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: coinprice
  labels:
    name: coinprice
---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinprice-config
  namespace: coinprice
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
---
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coinprice-server-sa
  namespace: coinprice
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinprice-server
  namespace: coinprice
  labels:
    app: coinprice-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinprice-server
  template:
    metadata:
      labels:
        app: coinprice-server
    spec:
      serviceAccountName: coinprice-server-sa
      containers:
      - name: coinprice-server
        image: us-central1-docker.pkg.dev/devops-demo-coinprice/devops-example-coinprice/coinprice-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: coinprice-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /bitcoin
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /bitcoin
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
---
# service
apiVersion: v1
kind: Service
metadata:
  name: coinprice-service
  namespace: coinprice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: coinprice-server
---
# hpa
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coinprice-hpa
  namespace: coinprice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coinprice-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# networkpolicy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coinprice-network-policy
  namespace: coinprice
spec:
  podSelector:
    matchLabels:
      app: coinprice-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 5000
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 0.0.0.0/0
---
# poddisruptionbudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coinprice-pdb
  namespace: coinprice
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: coinprice-server